<a href="https://colab.research.google.com/github/RaisaTahasen/Project/blob/main/NLP/TF_IDF_Cosine_Similarity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1

In [ ]:
import nltk
nltk.download('popular')

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Do

True

In [ ]:
import nltk
nltk.download('nps_chat')


[nltk_data] Downloading package nps_chat to /root/nltk_data...
[nltk_data]   Package nps_chat is already up-to-date!


True

In [ ]:
from nltk.corpus import nps_chat

In [ ]:
#nltk.download('all')


[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root

True

In [ ]:
from nltk.book import *


Task 1a

In [ ]:
vocab_size = len(set(text1))
print(f"Number of unique words in Moby Dick {vocab_size}")

Number of unique words in Moby Dick 19317


Task 1b

In [ ]:
length = len(text1)
print(f"Total number of words in Moby Dick {length}")

Total number of words in Moby Dick 260819


Task 1c

In [ ]:
num_of_words ={}
for w in text1:
  if w in num_of_words:
     num_of_words[w]+=1
  else:
    num_of_words[w] = 1

print("Sample word counts (first 10):")
for i, (word, count) in enumerate(num_of_words.items()):
    print(f"{word} : {count}")
    if i >= 9:
        break

print(f"\nTotal unique words (including punctuation): {len(num_of_words)}")

Sample word counts (first 10):
[ : 3
Moby : 84
Dick : 84
by : 1137
Herman : 1
Melville : 1
1851 : 3
] : 1
ETYMOLOGY : 1
. : 6862

Total unique words (including punctuation): 19317


Task 1d

In [ ]:
sort = dict(sorted(num_of_words.items(),key=lambda item: item[1], reverse=True))
print("Top 10 most frequent words:")
for i, (word, count) in enumerate(sort.items()):
    print(f"{word} : {count}")
    if i >= 9:
        break


Top 10 most frequent words:
, : 18713
the : 13721
. : 6862
of : 6536
and : 6024
a : 4569
to : 4542
; : 4072
in : 3916
that : 2982


Task 1e

In [ ]:
import string
print("Top 10 frequent words except punctuation")
n=0
for i, (word, count) in enumerate(sort.items()):
    if word in string.punctuation:
      pass
    else:
      print(f"{word} : {count}")
      n+=1
    if n > 9:
        break

Top 10 frequent words except punctuation
the : 13721
of : 6536
and : 6024
a : 4569
to : 4542
in : 3916
that : 2982
his : 2459
it : 2209
I : 2124


TASK 2a

In [ ]:
from google.colab import drive

drive.mount('/content/drive')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

file_path = "/content/drive/MyDrive/IMDB Dataset.csv"

df = pd.read_csv(file_path)

# Display the first few rows
print(df.head())


                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive


In [ ]:
num_of_reviews = len(df)
print(f"Number of reviews {num_of_reviews}")

Number of reviews 50000


In [ ]:
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [ ]:
# Function to count words
def count_num_of_words(text):
    return len(word_tokenize(text))

# Function to count sentences
def count_num_of_sentences(text):
    return len(sent_tokenize(text))

# Add word and sentence counts as new columns in the DataFrame
df['WordCount'] = df['review'].apply(count_num_of_words)
df['SentenceCount'] = df['review'].apply(count_num_of_sentences)


word_index = df['WordCount'].idxmax()
longest_word_review = df.loc[word_index]

sen_index = df['SentenceCount'].idxmax()
longest_sentence_review = df.loc[sen_index]

In [ ]:
print("Longest review in terms of words:")
print(f"Review: {longest_word_review['review']}")
print(f"Word Count: {longest_word_review['WordCount']}")
print(f"Row Number: {word_index}")
print("\nLongest review in terms of sentences:")
print(f"Review: {longest_sentence_review['review']}")
print(f"Sentence Count: {longest_sentence_review['SentenceCount']}")
print(f"Row Number: {sen_index}")



Longest review in terms of words:
Review: There's a sign on The Lost Highway that says:<br /><br />*MAJOR SPOILERS AHEAD*<br /><br />(but you already knew that, didn't you?)<br /><br />Since there's a great deal of people that apparently did not get the point of this movie, I'd like to contribute my interpretation of why the plot makes perfect sense. As others have pointed out, one single viewing of this movie is not sufficient. If you have the DVD of MD, you can "cheat" by looking at David Lynch's "Top 10 Hints to Unlocking MD" (but only upon second or third viewing, please.) ;)<br /><br />First of all, Mulholland Drive is downright brilliant. A masterpiece. This is the kind of movie that refuse to leave your head. Not often are the comments on the DVDs very accurate, but Vogue's "It gets inside your head and stays there" really hit the mark.<br /><br />David Lynch deserves praise for creating a movie that not only has a beautifully stylish look to it - cinematography-wise, has great 

Task 2b

In [ ]:
from nltk.corpus import stopwords
nltk.download('stopwords')
import string
def clean_review(txt):

    stop_words = set(stopwords.words('english'))
    punctuation = string.punctuation

    words = word_tokenize(txt)

    cl_words = []
    for word in words:
       if word not in stop_words and word not in punctuation:
         cl_words.append(word)

    return ' '.join(cl_words)  # Join words back into a cleaned string

# Apply the cleaning function to the review column
df['CleanedReview'] = df['review'].apply(clean_review)

# Display the first few rows to verify
print(df[['review', 'CleanedReview']].head(3))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


                                              review  \
0  One of the other reviewers has mentioned that ...   
1  A wonderful little production. <br /><br />The...   
2  I thought this was a wonderful way to spend ti...   

                                       CleanedReview  
0  One reviewers mentioned watching 1 Oz episode ...  
1  A wonderful little production br br The filmin...  
2  I thought wonderful way spend time hot summer ...  


Task 2c

In [ ]:
df['CleanedReview'] = df['CleanedReview'].str.lower()

with open('cleaned_reviews.txt', 'w') as file:
    for r in df['CleanedReview']:
        file.write(r + '\n')

with open('cleaned_reviews.txt', 'r') as file:
    lines = file.readlines()
    print(f"Total reviews saved: {len(lines)}")
    print(f"Total reviews in DataFrame: {len(df)}")

print(df['CleanedReview'].head(3))

Total reviews saved: 50000
Total reviews in DataFrame: 50000
0    one reviewers mentioned watching 1 oz episode ...
1    a wonderful little production br br the filmin...
2    i thought wonderful way spend time hot summer ...
Name: CleanedReview, dtype: object


Task 3a

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


tfidf_vectorizer = TfidfVectorizer()


tfidf_matrix = tfidf_vectorizer.fit_transform(df['CleanedReview'])


word_counts = (tfidf_matrix > 0).sum(axis=1).A1
print(f"\nTF-IDF Matrix Shape: {tfidf_matrix.shape}")
print(f"\nVocabulary Size: {tfidf_matrix.shape[1]}")

print("\nSparse TF-IDF Matrix (First 5 Rows, 10 Features):")
print(tfidf_matrix[:5, :10].toarray())  # First 5 rows, first 10 columns

feature_names = tfidf_vectorizer.get_feature_names_out()[:10]
print("\nFeature Names for First 10 Features:")
print(feature_names)


# max_word_count = word_counts.max()

# max_word_count_index = word_counts.argmax()

# print("\nReview with highest word count:")
# print(f"Word Count {max_word_count}")
# print(f"Row Count {max_word_count_index}")



TF-IDF Matrix Shape: (50000, 101880)

Vocabulary Size: 101880

Sparse TF-IDF Matrix (First 5 Rows, 10 Features):
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

Feature Names for First 10 Features:
['00' '000' '00000000000' '0000000000001' '00000001' '00001' '00015'
 '000dm' '000s' '001']


In [ ]:
# Get the feature names from the TF-IDF vectorizer
tfidf_vectorizer.get_feature_names_out()



array(['00', '000', '00000000000', ..., 'żmijewski', 'יגאל', 'כרמון'],
      dtype=object)

Task 3b

In [ ]:
import numpy as np
from numpy.linalg import norm
file_path = "/content/drive/MyDrive/glove.6B.100d.txt"

def load_embeddings(file_path):
    embeddings = {}
    with open(file_path, 'r', encoding='utf-8') as c:
        for line in c:
            val = line.split()
            word = val[0]
            vector = np.array(val[1:], dtype='float32')
            embeddings[word] = vector
    return embeddings

# Cosine similarity
def cos_similarity(vec1, vec2):
    return np.dot(vec1, vec2) / (norm(vec1) * norm(vec2))


glove_file = file_path

embeddings = load_embeddings(glove_file)


words = ['man', 'woman', 'cat', 'dog', 'king', 'queen']
vectors = {word: embeddings[word] for word in words}

# Compute cosine similarities
similarities = {
    ("man and woman"): cos_similarity(vectors["man"], vectors["woman"]),
    ("cat and dog"): cos_similarity(vectors["cat"], vectors["dog"]),
    ("king and queen"): cos_similarity(vectors["king"], vectors["queen"]),
}


king_man_woman = vectors["king"] - vectors["man"] + vectors["woman"]


queen_similarity = cos_similarity(king_man_woman, vectors["queen"])

print("Cosine Similarities:")
for pair, sim in similarities.items():
    print(f"{pair} : {sim:.4f}")

print(f"\nKing - Man + Woman = Queen: {queen_similarity:.4f}")


Cosine Similarities:
man and woman : 0.8323
cat and dog : 0.8798
king and queen : 0.7508

King - Man + Woman = Queen: 0.7834
